### ISSUE TITLE
Multiple issues. use this for a TODO list, I guess.

### ISSUE THREAD

**Issue by WhosPix3l** [anthonyhfm/Mathmatica#6]
- [x] Apollo brightness broken
- [x] Fader mode isn't implemented
- [x] Live mode isn't implemented
- [x] Support for custom modes
- [ ] ~~Brightness also broken on palette editor, it seems like.~~

Remember, don't rush it, take your time (:
